using System.Collections.Generic;

namespace DWMPHorde
{
    /// <summary>
    /// Russian for the mod's text. Keys are the exact English the code shows; patterns cover
    /// text with numbers or a nested reason in it. Menu button labels are capitals like vanilla's.
    /// </summary>
    public static partial class Loc
    {
        private static readonly Dictionary<string, string> RuExact = new Dictionary<string, string> // process-scoped: constant table
        {
            // Title button and multiplayer panel (tk2d labels).
            { "MULTIPLAYER", "СЕТЕВАЯ ИГРА" },
            { "HOST", "СОЗДАТЬ" },
            { "JOIN", "ПОДКЛЮЧИТЬСЯ" },
            { "SETTINGS", "НАСТРОЙКИ" },
            { "DISCONNECT", "ОТКЛЮЧИТЬСЯ" },
            { "BACK", "НАЗАД" },
            { "HOST LAN", "СОЗДАТЬ (LAN)" },
            { "HOST STEAM", "СОЗДАТЬ (STEAM)" },
            { "JOIN LAN", "ПОДКЛЮЧИТЬСЯ (LAN)" },
            { "JOIN STEAM", "ПОДКЛЮЧИТЬСЯ (STEAM)" },
            { "HOSTING — LOAD SAVE", "ХОСТ — ЗАГРУЗИТЕ ИГРУ" },
            { "CHOOSE SLOT", "ВЫБЕРИТЕ СЛОТ" },
            { "ENTER WORLD", "ВОЙТИ В МИР" },
            { "STEAM…", "STEAM…" },
            { "CONNECTING…", "ПОДКЛЮЧЕНИЕ…" },
            { "PORT IN USE", "ПОРТ ЗАНЯТ" },
            { "STEAM NOT READY", "STEAM НЕ ГОТОВ" },
            { "BAD LOBBY ID", "НЕВЕРНЫЙ ID ЛОББИ" },
            { "LOBBY MISSING", "ЛОББИ НЕ НАЙДЕНО" },
            { "ALREADY ONLINE", "УЖЕ В СЕТИ" },
            { "HOST FAILED", "ОШИБКА ХОСТА" },
            { "JOIN FAILED", "ОШИБКА ПОДКЛЮЧЕНИЯ" },
            { "SET LOBBY ID", "УКАЖИТЕ ID ЛОББИ" },
            { "SHARE FAIL", "ОШИБКА ПЕРЕДАЧИ" },
            { "WRONG SAVE", "НЕ ТО СОХРАНЕНИЕ" },
            { "LOADING…", "ЗАГРУЗКА…" },
            { "DOWNLOADING…", "СКАЧИВАНИЕ…" },
            { "WAIT HOST…", "ЖДЕМ ХОСТА…" },
            { "WAITING…", "ОЖИДАНИЕ…" },
            { "REQUESTING WORLD…", "ЗАПРОС МИРА…" },
            { "CONNECTED", "ПОДКЛЮЧЕНО" },
            { "HOST READY", "ХОСТ ГОТОВ" },

            // Connection and world share status (F2 window, menu, HUD).
            { "Offline", "Не в сети" },
            { "No network", "Нет сети" },
            { "Connected to host", "Подключено к хосту" },
            { "Steam host — creating lobby…", "Хост Steam — создание лобби…" },
            { "Steam host failed", "Не удалось создать игру в Steam" },
            { "Invalid Steam lobby id", "Неверный ID лобби Steam" },
            { "Steam join failed", "Не удалось подключиться через Steam" },
            { "Steam joining lobby…", "Вход в лобби Steam…" },
            { "Steam: no host steam id", "Steam: нет Steam ID хоста" },
            { "Steam migrating — handshaking…", "Steam: смена хоста — соединение…" },
            { "Steam connected — handshaking…", "Steam подключен — соединение…" },
            { "Steam SNS failed", "Ошибка соединения Steam" },
            { "Host lost — migration failed", "Хост потерян — смена хоста не удалась" },
            { "Host lost — no route to new host", "Хост потерян — новый хост недоступен" },
            { "Host lost — bad Steam route", "Хост потерян — нет связи через Steam" },
            { "Migrating — Steam connect failed, retrying…", "Смена хоста — Steam не подключился, повтор…" },
            { "Host grant failed (port busy)", "Не удалось стать хостом (порт занят)" },
            { "Host grant failed (Steam)", "Не удалось стать хостом (Steam)" },
            { "Reconnected — co-op sync…", "Переподключено — синхронизация…" },
            { "Connected — waiting for host to enter world…", "Подключено — ждем, пока хост войдет в мир…" },
            { "Host ready — waiting for world download…", "Хост готов — ждем загрузки мира…" },
            { "Requesting host world…", "Запрос мира хоста…" },
            { "Waiting for host to enter world…", "Ждем, пока хост войдет в мир…" },
            { "Load the save again to host it (it was loaded before hosting)", "Загрузите сохранение еще раз, чтобы раздать его (оно загружено до создания игры)" },
            { "You are host now — press F3 to save when ready (auto-save on promote is disabled)", "Теперь вы хост — нажмите F3, чтобы сохранить игру (автосохранение при смене хоста отключено)" },
            { "Preparing world share…", "Подготовка мира к передаче…" },
            { "Resending world…", "Повторная отправка мира…" },
            { "Host not ready — enter world first", "Хост не готов — сначала войдите в мир" },
            { "No clients connected", "Нет подключенных игроков" },
            { "World share already in progress", "Передача мира уже идет" },
            { "Loading host world (offline)…", "Загрузка мира хоста (офлайн)…" },
            { "Receiving host world…", "Получение мира хоста…" },
            { "Verifying host world package…", "Проверка мира хоста…" },
            { "Checking for matching local world…", "Поиск такого же мира на этом компьютере…" },
            { "Chapter world received — waiting for the host", "Мир главы получен — ждем хоста" },
            { "Pick a profile slot for permanent world copy", "Выберите профиль для постоянной копии мира" },
            { "Multiplayer disabled: game patches were not applied (see log).", "Сетевая игра отключена: патчи игры не применились (см. лог)." },
            { "Multiplayer disabled: Harmony patching crashed (see log).", "Сетевая игра отключена: сбой при установке патчей (см. лог)." },

            // Reasons inside WORLD SHARE FAILED / WRONG SAVE / Error lines.
            { "unknown", "неизвестно" },
            { "campaign mismatch", "другая кампания" },
            { "host reported failure", "хост сообщил об ошибке" },
            { "host refused the chapter load", "хост отклонил загрузку главы" },
            { "chapter world never arrived from the host", "мир главы так и не пришел от хоста" },
            { "your loaded world has no co-op campaign id — load your co-op copy of the host's world, or leave and rejoin from the title screen to download it",
              "в загруженном мире нет ID кооперативной кампании — загрузите свою копию мира хоста или выйдите и подключитесь заново из главного меню, чтобы скачать его" },
            { "your loaded world belongs to a different campaign than the host's — leave and rejoin from the title screen to download the host's world",
              "загруженный мир из другой кампании, чем у хоста — выйдите и подключитесь заново из главного меню, чтобы скачать мир хоста" },
            { "character backup does not match this co-op campaign — kept loaded character", "резервная копия персонажа не из этой кампании — оставлен загруженный персонаж" },
            { "stale character backup refused — kept loaded character", "устаревшая копия персонажа отклонена — оставлен загруженный персонаж" },
            { "character backup belongs to a different co-op campaign — restore refused", "копия персонажа из другой кооперативной кампании — восстановление отклонено" },
            { "campaign mismatch, empty, or stale backup — restore refused", "другая кампания, пустая или устаревшая копия — восстановление отклонено" },

            // HUD lines.
            { "Someone is already talking to them…", "С ними уже кто-то говорит…" },
            { "They're not talking anymore.", "Разговор уже окончен." },
            { "Someone already handed that over.", "Это уже кто-то отдал." },
            { "Already taken…", "Уже забрали…" },
            { "Could not place — returned to bag", "Не удалось положить — возвращено в сумку" },
            { "This object is already being moved by another player", "Этот предмет уже двигает другой игрок" },

            // F2 window.
            { "Status:", "Статус:" },
            { "Join: host must be in-chapter → world share → pick slot → ENTER WORLD.", "Подключение: хост в главе → передача мира → выбор профиля → ВОЙТИ В МИР." },
            { "Host IP:", "IP хоста:" },
            { "Port (1-65535):", "Порт (1-65535):" },
            { "Password (optional):", "Пароль (необязательно):" },
            { "Steam lobby id:", "ID лобби Steam:" },
            { "Chat name:", "Имя в чате:" },
            { "Apply", "Применить" },
            { "Saved", "Сохранено" },
            { "Advanced ▾", "Дополнительно ▾" },
            { "Advanced ▸", "Дополнительно ▸" },
            { "Lobby:", "Лобби:" },
            { "Copy lobby id + open invite", "Скопировать ID лобби и пригласить" },
            { "Resend world to clients", "Отправить мир игрокам заново" },
            { "Disconnect", "Отключиться" },
            { "F2=settings F3=save", "F2 — настройки, F3 — сохранение" },
            { "Client self-backup (inv / skills / exit pos):", "Резервная копия персонажа (инвентарь / навыки / место выхода):" },
            { "On disk: none for this campaign.", "На диске: нет для этой кампании." },
            { "Restore self now", "Восстановить персонажа" },
            { "Need to be in-chapter (not title). Auto-restore runs on join.", "Нужно быть в игре (не в главном меню). При подключении восстановление идет само." },
            { "Host uses sav.dat — restore self is client-only (would overwrite host).", "Хост использует sav.dat — восстановление только для подключившихся игроков." },
            { "No usable self-backup for this campaign yet (save / disconnect as client first).", "Для этой кампании еще нет копии персонажа (сначала сохранитесь или отключитесь как игрок)." },
            { "Restore blocked.", "Восстановление недоступно." },
            { "No local self-backup found.", "Копия персонажа не найдена." },

            // F3 window.
            { "Manual Saves (F3)", "Ручные сохранения (F3)" },
            { "No active profile", "Нет активного профиля" },
            { "[Empty]", "[Пусто]" },
            { "shared (old)", "общий (старый)" },
            { "Overwrite?", "Перезаписать?" },
            { "Load? (lose progress)", "Загрузить? (прогресс потеряется)" },
            { "Yes", "Да" },
            { "No", "Нет" },
            { "Save", "Сохр." },
            { "Load", "Загр." },
            { "Error: SaveManager not available", "Ошибка: SaveManager недоступен" },
            { "Blocked: only the host can save the co-op world (F3 on the host)", "Недоступно: кооперативный мир сохраняет только хост (F3 у хоста)" },
            { "Error: no active profile", "Ошибка: нет активного профиля" },
            { "Save did not write — try again in a moment", "Сохранение не записалось — попробуйте чуть позже" },
            { "Blocked: leave the co-op session first (F2 > Disconnect), then load", "Недоступно: сначала выйдите из сетевой игры (F2 > Отключиться), затем загружайтесь" },
            { "Blocked: wait until the game finishes loading", "Недоступно: дождитесь окончания загрузки" },
            { "partial night death", "часть игроков погибла ночью" },
            { "night death held", "смерть ночью до утра" },
            { "dream session", "сон" },
            { "prologue", "пролог" },
            { "application quitting", "выход из игры" },
            { "promoted host (survivor world is not authoritative)", "смена хоста (мир выжившего не основной)" },
            { "chapter transition", "переход между главами" },

            // Join slot picker.
            { "Permanent world copy — pick profile slot", "Постоянная копия мира — выберите профиль" },
            { "Host world downloaded. Choose which local PLAY profile keeps a permanent copy.", "Мир хоста скачан. Выберите профиль ИГРАТЬ, где будет храниться его постоянная копия." },
            { "It stays on this machine until you delete that profile. Live co-op still uses the host's world.", "Копия останется на этом компьютере, пока вы не удалите профиль. Сама игра идет в мире хоста." },
            { "Overwrite with the host world? This cannot be undone.", "Перезаписать миром хоста? Это нельзя отменить." },
            { "Overwrite will replace that save with the host world.", "Перезапись заменит это сохранение миром хоста." },
            { "Overwrite & keep permanently", "Перезаписать и сохранить навсегда" },
            { "Cancel", "Отмена" },
            { "(last used)", "(последний)" },
            { "[Empty] — safe to use", "[Пусто] — можно использовать" },
            { "[SAME AS HOST]", "[КАК У ХОСТА]" },
            { "[DIFFERENT CAMPAIGN]", "[ДРУГАЯ КАМПАНИЯ]" },
            { "Co-op copy", "Копия для кооператива" },
            { "Campaign", "Кампания" },
            { "Use empty", "Занять" },
            { "Update copy", "Обновить" },
            { "Overwrite", "Перезаписать" },
            { "Tip: empty slots first. Deleting a profile in PLAY removes the permanent copy.", "Совет: сначала пустые профили. Удаление профиля в ИГРАТЬ удаляет и копию." },
            { "Failed to save world copy", "Не удалось сохранить копию мира" },
            { "No host world package waiting for a slot", "Нет мира хоста, ожидающего выбора профиля" },
            { "Invalid profile slot (use 1–5)", "Неверный профиль (1–5)" },
            { "Profile", "Профиль" },
            { "Slot", "Слот" },
            { "Day", "День" },
            { "Ch.", "Гл." },

            // Walkie-talkie item (vanilla Items sheet).
            { "Walkie-Talkie", "Рация" },
            { "A crude two-way radio. Carry one each to talk over any distance.", "Самодельная рация. Возьмите каждый по одной — и говорите на любом расстоянии." },

            // Chat and map pins.
            { "Chat  —  ENTER send   ESC close", "Чат  —  ENTER отправить   ESC закрыть" },
            { "SEND", "ОТПР." },
            { "[System] Not in a session.", "[Система] Вы не в сетевой игре." },
            { "you", "вы" },
            { "someone", "кто-то" },
            { "Mark", "Метка" },
            { "Danger", "Опасность" },
            { "Loot", "Добыча" },
            { "Shelter", "Укрытие" },
            { "Camp", "Лагерь" },
            { "Grave", "Могила" },
            { "RMB erase · wheel restyle · double-click label", "ПКМ — стереть · колесо — сменить вид · двойной щелчок — подпись" },
            { "Label (Enter save, Esc cancel)", "Подпись (Enter — сохранить, Esc — отмена)" },
        };

        private static readonly Pattern[] RuPatterns = // process-scoped: constant table
        {
            P(@"Player (\d+) connected", m => "Игрок " + V(m, 1) + " подключился"),
            P(@"Player (\d+) joined", m => "Игрок " + V(m, 1) + " вошел в игру"),
            P(@"Player (\d+) left \((\d+) remaining, ready=(\d+)\)", m => "Игрок " + V(m, 1) + " вышел (осталось " + V(m, 2) + ", готовы " + V(m, 3) + ")"),
            P(@"Steam player (\d+) connected", m => "Игрок Steam " + V(m, 1) + " подключился"),
            P(@"Steam player (\d+) left \((\d+) remaining\)", m => "Игрок Steam " + V(m, 1) + " вышел (осталось " + V(m, 2) + ")"),
            P(@"Error: (.*)", m => "Ошибка: " + G(m, 1)),
            P(@"Failed to bind port (\d+)", m => "Не удалось занять порт " + V(m, 1)),
            P(@"Hosting on port (\d+)", m => "Хост на порту " + V(m, 1)),
            P(@"Connecting to (.+)", m => "Подключение к " + V(m, 1)),
            P(@"Steam unavailable: (.*)", m => "Steam недоступен: " + G(m, 1)),
            P(@"Steam hosting lobby (\d+)", m => "Хост Steam, лобби " + V(m, 1)),
            P(@"Steam lobby failed: (.*)", m => "Ошибка лобби Steam: " + G(m, 1)),
            P(@"Reconnect failed \((.*)\) — retry (\d+)/(\d+) in (\d+)s", m => "Переподключение не удалось (" + G(m, 1) + ") — попытка " + V(m, 2) + "/" + V(m, 3) + " через " + V(m, 4) + " с"),
            P(@"Could not reconnect to the host \((.*)\)", m => "Не удалось переподключиться к хосту (" + G(m, 1) + ")"),
            P(@"Connection failed \((.*)\)", m => "Не удалось подключиться (" + G(m, 1) + ")"),
            P(@"Handing host to p(\d+)…", m => "Передача хоста игроку p" + V(m, 1) + "…"),
            P(@"Host lost — reconnecting to p(\d+)…", m => "Хост потерян — подключение к p" + V(m, 1) + "…"),
            P(@"HOST GRANTED — port (\d+) \(p(\d+)\)", m => "ВЫ ТЕПЕРЬ ХОСТ — порт " + V(m, 1) + " (p" + V(m, 2) + ")"),
            P(@"HOST GRANTED — Steam \(p(\d+)\)", m => "ВЫ ТЕПЕРЬ ХОСТ — Steam (p" + V(m, 1) + ")"),
            P(@"Synced — load (.+) \(ch(\d+)\)", m => "Синхронизировано — загрузите " + V(m, 1) + " (глава " + V(m, 2) + ")"),
            P(@"Compressing (.+) \((\d+) KB\)…", m => "Сжатие " + V(m, 1) + " (" + V(m, 2) + " КБ)…"),
            P(@"Sending world \(slot (\d+)\) (\d+)%", m => "Отправка мира (профиль " + V(m, 1) + ") " + V(m, 2) + "%"),
            P(@"Sending world to player (\d+)…", m => "Отправка мира игроку " + V(m, 1) + "…"),
            P(@"World shared → client profile (\d+)", m => "Мир передан → профиль игрока " + V(m, 1)),
            P(@"Receiving host world (\d+)%", m => "Получение мира хоста " + V(m, 1) + "%"),
            P(@"Same world already on Profile (\d+) — press ENTER WORLD", m => "Этот мир уже есть в профиле " + V(m, 1) + " — нажмите ВОЙТИ В МИР"),
            P(@"Permanent copy on Profile (\d+) — press ENTER WORLD", m => "Постоянная копия в профиле " + V(m, 1) + " — нажмите ВОЙТИ В МИР"),
            P(@"Slot (\d+) already has a save — confirm overwrite", m => "В профиле " + V(m, 1) + " уже есть сохранение — подтвердите перезапись"),
            P(@"Multiplayer disabled: (\d+) critical game patch\(es\) failed \(mod/game version mismatch\?\)\. See log\.",
                m => "Сетевая игра отключена: не применились важные патчи игры (" + V(m, 1) + ") — версии мода и игры не совпадают? См. лог."),
            P(@"(\d+) cosmetic patch\(es\) failed; multiplayer still allowed\.", m => "Не применились второстепенные патчи (" + V(m, 1) + "); сетевая игра доступна."),
            P(@"WORLD SHARE FAILED: (.*?) — do not continue \(different forests\)\. Host: save once, F2 Resend, or rejoin\.(?: The host has moved on to chapter (\d+)\.)?",
                m => "ПЕРЕДАЧА МИРА НЕ УДАЛАСЬ: " + G(m, 1)
                    + " — не продолжайте (у вас будут разные леса). Хост: сохраните игру и нажмите F2 → «Отправить мир игрокам заново», или подключитесь заново."
                    + (m.Groups[2].Success ? " Хост уже перешел к главе " + V(m, 2) + "." : "")),
            P(@"WRONG SAVE: (.*)", m => "НЕ ТО СОХРАНЕНИЕ: " + G(m, 1)),
            P(@"your world is still chapter (\d+) after a resync; the host is in chapter (\d+) — leave and rejoin from the title screen",
                m => "после синхронизации ваш мир все еще в главе " + V(m, 1) + ", а хост в главе " + V(m, 2) + " — выйдите и подключитесь заново из главного меню"),
            P(@"host world could not be written after (\d+) retries", m => "мир хоста не удалось записать после " + V(m, 1) + " попыток"),
            P(@"host never confirmed the chapter load within (\d+)s", m => "хост не подтвердил загрузку главы за " + V(m, 1) + " с"),
            P(@"chapter world could not be written or entered: (.*)", m => "мир главы не удалось записать или открыть: " + G(m, 1)),
            P(@"chapter world could not be written: (.*)", m => "мир главы не удалось записать: " + G(m, 1)),
            P(@"host world package could not be verified: (.*)", m => "мир хоста не прошел проверку: " + G(m, 1)),
            P(@"no save files for prof(\d+) — host: save once then Resend", m => "нет файлов сохранения профиля " + V(m, 1) + " — хост: сохраните игру и отправьте мир заново"),
            P(@"Profile (\d+) belongs to a different co-op campaign than this host\.", m => "Профиль " + V(m, 1) + " принадлежит другой кооперативной кампании, чем у этого хоста."),
            P(@"Profile (\d+) already has a save\.", m => "В профиле " + V(m, 1) + " уже есть сохранение."),
            P(@"Blocked: cannot save during (.+)", m => "Недоступно: нельзя сохраняться — " + G(m, 1)),
            P(@"Save error: (.*)", m => "Ошибка сохранения: " + V(m, 1)),
            P(@"Load error: (.*)", m => "Ошибка загрузки: " + V(m, 1)),
            P(@"Saved to slot (\d+)", m => "Сохранено в слот " + V(m, 1)),
            P(@"Slot (\d+) is empty", m => "Слот " + V(m, 1) + " пуст"),
            P(@"Co-op copy( · joined (.+?)| · refreshed (.+?))?( · (.+))?",
                m => "Копия для кооператива"
                    + (m.Groups[2].Success ? " · подключение " + V(m, 2) : m.Groups[3].Success ? " · обновлено " + V(m, 3) : "")
                    + (m.Groups[5].Success ? " · " + V(m, 5) : "")),
        };
    }
}
