using System.Collections.Generic;

namespace DWMPHorde
{
    /// <summary>
    /// Russian for the mod's text. Keys are the exact English the code shows; patterns cover
    /// text with numbers or a nested reason in it.
    /// </summary>
    public static partial class Loc
    {
        private static readonly Dictionary<string, string> RuExact = new Dictionary<string, string> // process-scoped: constant table
        {
            // Title / pause button and the multiplayer screens.
            { "MULTIPLAYER", "СЕТЕВАЯ ИГРА" },
            { "Multiplayer", "Сетевая игра" },
            { "Host", "Создать игру" },
            { "Join", "Подключиться" },
            { "Host this game", "Открыть эту игру для других" },
            { "Choose a profile", "Выбрать профиль" },
            { "Enter world", "Войти в мир" },
            { "Invite friends", "Пригласить друзей" },
            { "Send the world again", "Отправить мир заново" },
            { "Restore my character", "Восстановить персонажа" },
            { "Settings", "Настройки" },
            { "Host settings", "Настройки хоста" },
            { "Creatures hear voices", "Твари слышат голоса" },
            { "Voice", "Голос" },
            { "Microphone", "Микрофон" },
            { "Microphone volume", "Громкость микрофона" },
            { "Microphone level", "Уровень микрофона" },
            { "Default", "По умолчанию" },
            { "not found", "не найден" },
            { "Nobody yet", "Пока никого" },
            { "Voice chat is off", "Голосовой чат выключен" },
            { "No microphone found", "Микрофон не найден" },
            { "Starting...", "Запуск..." },
            { "talking", "говорите" },
            { "No other players in this game.", "Других игроков в этой игре нет." },
            { "Disconnect", "Отключиться" },
            { "Local network", "Локальная сеть" },
            { "Steam", "Steam" },
            { "Connect", "Соединиться" },
            { "Join the lobby", "Войти в лобби" },
            { "Cancel", "Отмена" },
            { "Address", "Адрес" },
            { "Port", "Порт" },
            { "Password", "Пароль" },
            { "Steam lobby", "Лобби Steam" },
            { "Name", "Имя" },
            { "Text chat", "Текстовый чат" },
            { "Player names", "Имена игроков" },
            { "When pointed at", "При наведении" },
            { "Always", "Всегда" },
            { "Say:", "Сказать:" },
            { "Voice chat", "Голосовой чат" },
            { "Push to talk key", "Клавиша рации" },
            { "Voice volume", "Громкость голоса" },
            { "Other players' steps", "Шаги других игроков" },
            { "Friendly fire", "Огонь по своим" },
            { "Extra loot", "Больше добычи" },
            { "Night monsters", "Ночные твари" },
            { "x1", "×1" },
            { "x1.5", "×1,5" },
            { "x2", "×2" },
            { "x3", "×3" },
            { "x4", "×4" },
            { "x5", "×5" },
            { "x7", "×7" },
            { "x10", "×10" },
            { "Players", "Игроков" },
            { "Press a key", "Нажмите клавишу" },
            { "Yes", "Да" },
            { "No", "Нет" },
            { "Off", "Выкл." },
            { "Push to talk", "По нажатию" },
            { "Always on", "Всегда" },
            { "Friends only", "Только друзья" },
            { "Public", "Открытое" },
            { "Invite only", "По приглашению" },
            { "Grows with the party", "Растет с числом игроков" },
            { "Hosting a Steam game", "Игра в Steam создана" },
            { "Hosting on the local network", "Игра в локальной сети создана" },
            { "Lobby id copied — invite friends in the Steam overlay", "ID лобби скопирован — пригласите друзей через оверлей Steam" },
            { "Nobody has joined yet", "Пока никто не подключился" },
            { "The world is already being sent", "Мир уже отправляется" },
            { "Sending the world to the other players…", "Отправка мира другим игрокам…" },
            { "Stop hosting? The other players are moved to a new host when one can take over.", "Закрыть игру? Другие игроки перейдут к новому хосту, если он найдется." },
            { "Leave the game?", "Выйти из игры?" },
            { "Choose a profile next. Other players join once you are in the game.", "Дальше выберите профиль. Другие игроки подключатся, когда вы будете в игре." },
            { "Other players get a copy of this world when they join.", "Подключившиеся игроки получат копию этого мира." },
            { "Already in a game — disconnect first", "Вы уже в сетевой игре — сначала отключитесь" },
            { "Could not start hosting", "Не удалось создать игру" },
            { "Type in the Steam lobby id, or accept an invite in Steam", "Введите ID лобби Steam или примите приглашение в Steam" },
            { "Could not join the lobby", "Не удалось войти в лобби" },
            { "Could not reach the host through Steam", "Не удалось связаться с хостом через Steam" },
            { "Could not reach the host — check the address, port and password", "Не удалось связаться с хостом — проверьте адрес, порт и пароль" },
            { "The port is already in use", "Порт уже занят" },
            { "Steam is not running", "Steam не запущен" },
            { "That is not a Steam lobby id", "Это не ID лобби Steam" },
            { "The Steam lobby is gone", "Лобби Steam больше нет" },
            { "Connecting…", "Подключение…" },
            { "Connecting through Steam…", "Подключение через Steam…" },
            { "Connected", "Подключено" },
            { "Connected — asking the host for the world…", "Подключено — запрос мира у хоста…" },
            { "Connected — waiting for the host to enter the game…", "Подключено — ждем, пока хост войдет в игру…" },
            { "The host's world could not be copied", "Мир хоста не удалось скопировать" },
            { "Choose the profile that keeps the host's world", "Выберите профиль для мира хоста" },
            { "The host's world is ready", "Мир хоста готов" },
            { "The host's world", "Мир хоста" },
            { "Choose the profile that keeps a copy of the host's world. It stays on this computer until you delete the profile.",
              "Выберите профиль, где будет храниться копия мира хоста. Она останется на этом компьютере, пока вы не удалите профиль." },
            { "Empty", "Пусто" },
            { "Co-op copy", "Копия для кооператива" },
            { "same world", "тот же мир" },
            { "Your game", "Ваша игра" },
            { "another campaign", "другая кампания" },
            { "last used", "последний" },
            { "Overwrite", "Перезаписать" },
            { "Put back your character from the last backup?", "Вернуть персонажа из последней резервной копии?" },
            { "level", "уровень" },
            { "items", "предметы" },
            { "No backup of your character yet", "Резервной копии персонажа пока нет" },
            { "Character restored", "Персонаж восстановлен" },

            // Connection and world share status (multiplayer screens, HUD).
            { "Offline", "Не в сети" },
            { "No network", "Нет сети" },
            { "Connected to host", "Подключено к хосту" },
            { "Steam host — creating lobby…", "Хост Steam — создание лобби…" },
            { "Steam host failed", "Не удалось создать игру в Steam" },
            { "Invalid Steam lobby id", "Неверный ID лобби Steam" },
            { "Steam join failed", "Не удалось подключиться через Steam" },
            { "Steam joining lobby…", "Вход в лобби Steam…" },
            { "Steam: no host steam id", "Steam: нет Steam ID хоста" },
            { "Steam migrating — handshaking…", "Steam: смена хоста — соединение…" },
            { "Steam connected — handshaking…", "Steam подключен — соединение…" },
            { "Steam SNS failed", "Ошибка соединения Steam" },
            { "Host lost — migration failed", "Хост потерян — смена хоста не удалась" },
            { "Host lost — no route to new host", "Хост потерян — новый хост недоступен" },
            { "Host lost — bad Steam route", "Хост потерян — нет связи через Steam" },
            { "Migrating — Steam connect failed, retrying…", "Смена хоста — Steam не подключился, повтор…" },
            { "Host grant failed (port busy)", "Не удалось стать хостом (порт занят)" },
            { "Host grant failed (Steam)", "Не удалось стать хостом (Steam)" },
            { "Reconnected — co-op sync…", "Переподключено — синхронизация…" },
            { "Connected — waiting for host to enter world…", "Подключено — ждем, пока хост войдет в мир…" },
            { "Host ready — waiting for world download…", "Хост готов — ждем загрузки мира…" },
            { "Requesting host world…", "Запрос мира хоста…" },
            { "Waiting for host to enter world…", "Ждем, пока хост войдет в мир…" },
            { "Load the save again to host it (it was loaded before hosting)", "Загрузите сохранение еще раз, чтобы раздать его (оно загружено до создания игры)" },
            { "You are host now — the world is saved again at the game's next save", "Теперь вы хост — мир сохранится при следующем сохранении игры" },
            { "Preparing world share…", "Подготовка мира к передаче…" },
            { "Resending world…", "Повторная отправка мира…" },
            { "Host not ready — enter world first", "Хост не готов — сначала войдите в мир" },
            { "No clients connected", "Нет подключенных игроков" },
            { "World share already in progress", "Передача мира уже идет" },
            { "Loading host world (offline)…", "Загрузка мира хоста (офлайн)…" },
            { "Receiving host world…", "Получение мира хоста…" },
            { "Verifying host world package…", "Проверка мира хоста…" },
            { "Checking for matching local world…", "Поиск такого же мира на этом компьютере…" },
            { "Chapter world received — waiting for the host", "Мир главы получен — ждем хоста" },
            { "Pick a profile slot for permanent world copy", "Выберите профиль для постоянной копии мира" },
            { "Multiplayer disabled: game patches were not applied (see log).", "Сетевая игра отключена: патчи игры не применились (см. лог)." },
            { "Multiplayer disabled: Harmony patching crashed (see log).", "Сетевая игра отключена: сбой при установке патчей (см. лог)." },

            // Reasons inside WORLD SHARE FAILED / WRONG SAVE / Error lines.
            { "unknown", "неизвестно" },
            { "campaign mismatch", "другая кампания" },
            { "host reported failure", "хост сообщил об ошибке" },
            { "host refused the chapter load", "хост отклонил загрузку главы" },
            { "chapter world never arrived from the host", "мир главы так и не пришел от хоста" },
            { "your loaded world has no co-op campaign id — load your co-op copy of the host's world, or leave and rejoin from the title screen to download it",
              "в загруженном мире нет ID кооперативной кампании — загрузите свою копию мира хоста или выйдите и подключитесь заново из главного меню, чтобы скачать его" },
            { "your loaded world belongs to a different campaign than the host's — leave and rejoin from the title screen to download the host's world",
              "загруженный мир из другой кампании, чем у хоста — выйдите и подключитесь заново из главного меню, чтобы скачать мир хоста" },
            { "character backup does not match this co-op campaign — kept loaded character", "резервная копия персонажа не из этой кампании — оставлен загруженный персонаж" },
            { "stale character backup refused — kept loaded character", "устаревшая копия персонажа отклонена — оставлен загруженный персонаж" },
            { "character backup belongs to a different co-op campaign — restore refused", "копия персонажа из другой кооперативной кампании — восстановление отклонено" },
            { "campaign mismatch, empty, or stale backup — restore refused", "другая кампания, пустая или устаревшая копия — восстановление отклонено" },

            // HUD lines.
            { "Someone is already talking to them…", "С ними уже кто-то говорит…" },
            { "They're not talking anymore.", "Разговор уже окончен." },
            { "Someone already handed that over.", "Это уже кто-то отдал." },
            { "Already taken…", "Уже забрали…" },
            { "Could not place — returned to bag", "Не удалось положить — возвращено в сумку" },
            { "This object is already being moved by another player", "Этот предмет уже двигает другой игрок" },

            // Manual saves add-on (YokWare.ManualSaves, built with the co-op mod's menus).
            { "Saves", "Сохранения" },
            { "Slot", "Слот" },
            { "shared (old)", "общий (старый)" },
            { "Save", "Сохранить" },
            { "Load", "Загрузить" },
            { "Error: SaveManager not available", "Ошибка: SaveManager недоступен" },
            { "Blocked: only the host can save the co-op world", "Недоступно: кооперативный мир сохраняет только хост" },
            { "Error: no active profile", "Ошибка: нет активного профиля" },
            { "Save did not write — try again in a moment", "Сохранение не записалось — попробуйте чуть позже" },
            { "Blocked: leave the co-op session first (Multiplayer > Disconnect), then load", "Недоступно: сначала выйдите из сетевой игры (Сетевая игра > Отключиться), затем загружайтесь" },
            { "Blocked: wait until the game finishes loading", "Недоступно: дождитесь окончания загрузки" },
            { "partial night death", "часть игроков погибла ночью" },
            { "night death held", "смерть ночью до утра" },
            { "dream session", "сон" },
            { "prologue", "пролог" },
            { "application quitting", "выход из игры" },
            { "promoted host (survivor world is not authoritative)", "смена хоста (мир выжившего не основной)" },
            { "chapter transition", "переход между главами" },

            // Join flow messages.
            { "Overwrite with the host world? This cannot be undone.", "Перезаписать миром хоста? Это нельзя отменить." },
            { "Overwrite will replace that save with the host world.", "Перезапись заменит это сохранение миром хоста." },
            { "Failed to save world copy", "Не удалось сохранить копию мира" },
            { "No host world package waiting for a slot", "Нет мира хоста, ожидающего выбора профиля" },
            { "Invalid profile slot (use 1–5)", "Неверный профиль (1–5)" },

            // Walkie-talkie item (vanilla Items sheet).
            { "Walkie-Talkie", "Рация" },
            { "A crude two-way radio. Carry one each to talk over any distance.", "Самодельная рация. Возьмите каждый по одной — и говорите на любом расстоянии." },

            // Chat and map pins.
            { "[System] Not in a session.", "[Система] Вы не в сетевой игре." },
            { "you", "вы" },
            { "someone", "кто-то" },
            { "Mark", "Метка" },
            { "Danger", "Опасность" },
            { "Loot", "Добыча" },
            { "Shelter", "Укрытие" },
            { "Camp", "Лагерь" },
            { "Grave", "Могила" },
            { "RMB erase · wheel restyle · double-click label", "ПКМ — стереть · колесо — сменить вид · двойной щелчок — подпись" },
            { "Label (Enter save, Esc cancel)", "Подпись (Enter — сохранить, Esc — отмена)" },
        };

        private static readonly Pattern[] RuPatterns = // process-scoped: constant table
        {
            P(@"Player (\d+) connected", m => "Игрок " + V(m, 1) + " подключился"),
            P(@"Player (\d+) joined", m => "Игрок " + V(m, 1) + " вошел в игру"),
            P(@"Player (\d+) left \((\d+) remaining, ready=(\d+)\)", m => "Игрок " + V(m, 1) + " вышел (осталось " + V(m, 2) + ", готовы " + V(m, 3) + ")"),
            P(@"Steam player (\d+) connected", m => "Игрок Steam " + V(m, 1) + " подключился"),
            P(@"Steam player (\d+) left \((\d+) remaining\)", m => "Игрок Steam " + V(m, 1) + " вышел (осталось " + V(m, 2) + ")"),
            P(@"Error: (.*)", m => "Ошибка: " + G(m, 1)),
            P(@"Failed to bind port (\d+)", m => "Не удалось занять порт " + V(m, 1)),
            P(@"Hosting on port (\d+)", m => "Хост на порту " + V(m, 1)),
            P(@"Connecting to (.+)", m => "Подключение к " + V(m, 1)),
            P(@"Steam unavailable: (.*)", m => "Steam недоступен: " + G(m, 1)),
            P(@"Steam hosting lobby (\d+)", m => "Хост Steam, лобби " + V(m, 1)),
            P(@"Steam lobby failed: (.*)", m => "Ошибка лобби Steam: " + G(m, 1)),
            P(@"Reconnect failed \((.*)\) — retry (\d+)/(\d+) in (\d+)s", m => "Переподключение не удалось (" + G(m, 1) + ") — попытка " + V(m, 2) + "/" + V(m, 3) + " через " + V(m, 4) + " с"),
            P(@"Could not reconnect to the host \((.*)\)", m => "Не удалось переподключиться к хосту (" + G(m, 1) + ")"),
            P(@"Connection failed \((.*)\)", m => "Не удалось подключиться (" + G(m, 1) + ")"),
            P(@"Handing host to p(\d+)…", m => "Передача хоста игроку p" + V(m, 1) + "…"),
            P(@"Host lost — reconnecting to p(\d+)…", m => "Хост потерян — подключение к p" + V(m, 1) + "…"),
            P(@"HOST GRANTED — port (\d+) \(p(\d+)\)", m => "ВЫ ТЕПЕРЬ ХОСТ — порт " + V(m, 1) + " (p" + V(m, 2) + ")"),
            P(@"HOST GRANTED — Steam \(p(\d+)\)", m => "ВЫ ТЕПЕРЬ ХОСТ — Steam (p" + V(m, 1) + ")"),
            P(@"Synced — load (.+) \(ch(\d+)\)", m => "Синхронизировано — загрузите " + V(m, 1) + " (глава " + V(m, 2) + ")"),
            P(@"Compressing (.+) \((\d+) KB\)…", m => "Сжатие " + V(m, 1) + " (" + V(m, 2) + " КБ)…"),
            P(@"Sending world \(slot (\d+)\) (\d+)%", m => "Отправка мира (профиль " + V(m, 1) + ") " + V(m, 2) + "%"),
            P(@"Sending world to player (\d+)…", m => "Отправка мира игроку " + V(m, 1) + "…"),
            P(@"World shared → client profile (\d+)", m => "Мир передан → профиль игрока " + V(m, 1)),
            P(@"Receiving host world (\d+)%", m => "Получение мира хоста " + V(m, 1) + "%"),
            P(@"Same world already on Profile (\d+) — press Enter world", m => "Этот мир уже есть в профиле " + V(m, 1) + " — нажмите «Войти в мир»"),
            P(@"Permanent copy on Profile (\d+) — press Enter world", m => "Постоянная копия в профиле " + V(m, 1) + " — нажмите «Войти в мир»"),
            P(@"Slot (\d+) already has a save — confirm overwrite", m => "В профиле " + V(m, 1) + " уже есть сохранение — подтвердите перезапись"),
            P(@"Multiplayer disabled: (\d+) critical game patch\(es\) failed \(mod/game version mismatch\?\)\. See log\.",
                m => "Сетевая игра отключена: не применились важные патчи игры (" + V(m, 1) + ") — версии мода и игры не совпадают? См. лог."),
            P(@"(\d+) cosmetic patch\(es\) failed; multiplayer still allowed\.", m => "Не применились второстепенные патчи (" + V(m, 1) + "); сетевая игра доступна."),
            P(@"WORLD SHARE FAILED: (.*?) — do not continue \(different forests\)\. Host: save once, then Multiplayer > Send the world again; or rejoin\.(?: The host has moved on to chapter (\d+)\.)?",
                m => "ПЕРЕДАЧА МИРА НЕ УДАЛАСЬ: " + G(m, 1)
                    + " — не продолжайте (у вас будут разные леса). Хост: сохраните игру и выберите Сетевая игра > «Отправить мир заново», или подключитесь заново."
                    + (m.Groups[2].Success ? " Хост уже перешел к главе " + V(m, 2) + "." : "")),
            P(@"WRONG SAVE: (.*)", m => "НЕ ТО СОХРАНЕНИЕ: " + G(m, 1)),
            P(@"your world is still chapter (\d+) after a resync; the host is in chapter (\d+) — leave and rejoin from the title screen",
                m => "после синхронизации ваш мир все еще в главе " + V(m, 1) + ", а хост в главе " + V(m, 2) + " — выйдите и подключитесь заново из главного меню"),
            P(@"host world could not be written after (\d+) retries", m => "мир хоста не удалось записать после " + V(m, 1) + " попыток"),
            P(@"host never confirmed the chapter load within (\d+)s", m => "хост не подтвердил загрузку главы за " + V(m, 1) + " с"),
            P(@"chapter world could not be written or entered: (.*)", m => "мир главы не удалось записать или открыть: " + G(m, 1)),
            P(@"chapter world could not be written: (.*)", m => "мир главы не удалось записать: " + G(m, 1)),
            P(@"host world package could not be verified: (.*)", m => "мир хоста не прошел проверку: " + G(m, 1)),
            P(@"no save files for prof(\d+) — host: save once then Resend", m => "нет файлов сохранения профиля " + V(m, 1) + " — хост: сохраните игру и отправьте мир заново"),
            P(@"Profile (\d+) belongs to a different co-op campaign than this host\.", m => "Профиль " + V(m, 1) + " принадлежит другой кооперативной кампании, чем у этого хоста."),
            P(@"Profile (\d+) already has a save\.", m => "В профиле " + V(m, 1) + " уже есть сохранение."),
            P(@"Blocked: cannot save during (.+)", m => "Недоступно: нельзя сохраняться — " + G(m, 1)),
            P(@"Save error: (.*)", m => "Ошибка сохранения: " + V(m, 1)),
            P(@"Load error: (.*)", m => "Ошибка загрузки: " + V(m, 1)),
            P(@"Saved to slot (\d+)", m => "Сохранено в слот " + V(m, 1)),
            P(@"Overwrite slot (\d+)\?", m => "Перезаписать слот " + V(m, 1) + "?"),
            P(@"Load slot (\d+)\? Progress since your last save is lost\.", m => "Загрузить слот " + V(m, 1) + "? Прогресс после последнего сохранения пропадет."),
            P(@"(Hosting a Steam game|Hosting on the local network) — choose a profile to play", m => G(m, 1) + " — выберите профиль для игры"),
            P(@"(Hosting a Steam game|Hosting on the local network) — 1 player joined", m => G(m, 1) + " — подключился 1 игрок"),
            P(@"(Hosting a Steam game|Hosting on the local network) — (\d+) players joined", m => G(m, 1) + " — подключилось игроков: " + V(m, 2)),
            P(@"Slot (\d+) is empty", m => "Слот " + V(m, 1) + " пуст"),
            P(@"Co-op copy( · joined (.+?)| · refreshed (.+?))?( · (.+))?",
                m => "Копия для кооператива"
                    + (m.Groups[2].Success ? " · подключение " + V(m, 2) : m.Groups[3].Success ? " · обновлено " + V(m, 3) : "")
                    + (m.Groups[5].Success ? " · " + V(m, 5) : "")),
        };
    }
}
